- name: configure all servers
  hosts: general
  become: true
  tasks:
    - name: install epel release and ntp
      yum: name={{ item }} state=present
      with_items:
        - epel-release
        - ntp
    - name: start ntpd
      service: name=ntpd state=started

