---

- name: configure httpd
  hosts: web
  #vars:
  #  - env_name: production
  become: true
  tasks:
    - name: install apache
      yum: name=httpd state=present
    - name: debug
      debug: 
        msg: "{{ test_var }}"
    - name: start apache
      service: 
        name: httpd
        state: started
    - name: configure apache as proxy
      copy: 
        src: virtualhost.conf
        dest: /etc/httpd/conf.d/proxy.conf
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted


      
